stages:
  - deploy
deploy_development:
  stage: deploy
  script:
  - rsync -av * /var/www/dev.medbron.uz/ --no-perms --no-owner --no-group
  - cd /var/www/dev.medbron.uz/
<<<<<<< HEAD
  - php artisan migrate
=======
>>>>>>> origin
  - composer update --no-dev
  environment:
    name: development
    url: https://dev.medbron.uz
  only:
  - develop
deploy_production:
  stage: deploy
  script:
  - rsync -av * /var/www/prod.medbron.uz/ --no-perms --no-owner --no-group
  - cd /var/www/prod.medbron.uz/
<<<<<<< HEAD
  - php artisan migrate
=======
>>>>>>> origin
  - composer install
  environment:
    name: production
    url: https://prod.medbron.uz/
  only:
  - master