version: '3'
services:
  nginx:
    build: docker/nginx
    container_name: medical-booking-nginx
    ports:
      - 8081:80
    volumes:
      - ./:/var/www/html/
    links:
      - php-fpm
    networks:
      - internal
  php-fpm:
    build: docker/php-fpm
    container_name: medical-booking-php
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www/html/
    links:
      - db
      - redis
    networks:
      - internal
  db:
    image: postgres:12.2-alpine
    container_name: medical-booking-db-pg
    restart: unless-stopped
    ports:
      - 54321:5432
    volumes:
      - ./storage/docker/psql:/var/lib/postgresql/data:cached
    environment:
      - POSTGRES_DB=medical_booking
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=
    networks:
      - internal


      # db:
  #   image: mysql:5.7
  #   container_name: medical-booking-db
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - ./:/var/www/html/
  #     #- ./mail.sql:/docker-entrypoint-initdb.d/init.sql

  #   environment:
  #     MYSQL_DATABASE: medical_booking
  #     MYSQL_USER: root
  #     MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  #     MYSQL_PASSWORD:
  #     MYSQL_ROOT_PASSWORD:
  #   networks:
  #     - internal

  redis:
    image: redis
    container_name: medical-booking-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - ./:/var/www/html/
    networks:
      - internal
networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.221.0/28
