version: '3'
services:
  nginx:
    image: nginx:1.17-alpine
    container_name: medical-booking-nginx
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - 8081:80
    volumes:
      - ./:/var/www/html:cached
      - ./docker/nginx:/etc/nginx/conf.d:cached
    links:
      - php-fpm
    networks:
      - medical-booking

  php-fpm:
    build: docker/php-fpm
    container_name: medical-booking-php
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www/html:cached
    links:
      - db
      - redis
    networks:
      - medical-booking

  db:
    image: postgres:12.2-alpine
    container_name: medical-booking-db-pg
    restart: unless-stopped
    ports:
      - 54321:5432
    volumes:
      - ./:/var/www/html/
      #- ./storage/docker/psql:/var/lib/postgresql/data:cached
    environment:
      - POSTGRES_DB=medical_booking
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=booking123
    networks:
      - medical-booking

  redis:
    image: redis
    container_name: medical-booking-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - ./:/var/www/html:cached
    networks:
      - medical-booking

networks:
  medical-booking:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.219.0/28
